### ISSUE TITLE
ReiNX/Atmosphere?

### ISSUE THREAD

**Issue by lunalik2** [Plailect/Guide_Switch#49]
ReiNX has sig patches, and works fine. Using rajkosto's hekate, and/or ReiNX sig patches, atmosphere also has sig patches. ReiNX isn't fully done (no support for 1.0.0 and 3.0.2, and atmosphere isn't done either), but it works great on the working firmwares. Atmosphere is basically the same, and since it has layeredfs support, it is a viable alternative. Both of these are quite stable, so when would they be added in the guide??

**Comment by james-d-elliott** [comment]
I believe the short of it is that the process and the custom firmware all needs to be ready to ship to the average user. While it may work relatively well, there are currently guides for both of these"work in progress" custom firmwares to get the more advanced user up and running. Once Atmosphere is officially released (not work in progress) then I imagine a guide will exist.

**Comment by Plailect** [comment]
As I have said previously, I'm waiting for some stuff to stabilize a bit (hopefully whenever atmosphere releases) before recommending anything more than just homebrew launcher to regular users. Stuff like Hekate/ReiNX is only really good for people who are ready to constantly be updating all of their stuff all of the time (which some people enjoy, but those people also are the type to read forum/reddit posts constantly to stay up-to-speed and don't need a guide).

**Comment by lunalik2** [comment]
ReiNX just got it's first stable release. https://github.com/Reisyukaku/ReiNX/releases.

**Comment by Ninjistix** [comment]
#51 

they are other cfw's also, there's no point in being picky about which ones to  put on the guide, if they all work.
